m, n = int(input("Введите размер первого множества: ")), int(input("Введите размер второго множества: "))
print("Введите элементы первого множества: ")
nl = set([int(input()) for _ in range(m)])
print("Введите элементы второго множества: ")
ml = set([int(input()) for _ in range(n)])
print(*nl.intersection(ml))